/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   huffman_coding.c                                   :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: sguilher <sguilher@student.42sp.org.br>    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/01/10 13:42:12 by sguilher          #+#    #+#             */
/*   Updated: 2023/01/12 18:34:05 by sguilher         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "huffman.h"

/* Huffman coding:
	1. Count how many times each character is used - structure char and frequency - OK
	2. Order them in a list from the least used to the most used - OK
	3. Create the Huffman Tree: - OK!!
	- Put the 2 least used characters in the bottom branches and sum their frequencies into the top branch
	- Add the node sum back to the list, in the right order
	- Repeat the process until you have only one character on the list
	4. Create the encoding/translation table according with the Huffman Tree - OK
	5. Encode the text using the table - OK
	6. Decode the str of bits using the tree - OK
	7. Compression - transform the str of bits into real bits - OK
	8. Decompression - transform the bits into the string of bits
	close file
	*/

void	huffman_coding(void)
{
	unsigned char	initial_str[] = "Hello World";
	unsigned int	*freq;
	t_huffman		*head;
	char			**d;
	char			*str_bit1;
	char			*str_bit2;
	size_t			nbits;
	unsigned char	*bits;
	unsigned char	*final_str;

	printf("********** Initial string **********\n");
	printf("%s\n\n", initial_str);
	freq = huffman_frequency(initial_str);
	head = create_huffman_lst(freq);
	head = create_huffman_tree(&head);
	d = dictionary(head);
	str_bit1 = encode(d, initial_str);
	printf("********** String of bits from encode **********\n");
	printf("%s\n\n", str_bit1);
	nbits = number_of_bits(str_bit1);
	bits = compress(str_bit1, nbits);
	printf("********** String generated by compression **********\n");
	printf("%s\n\n", bits);
	printf("********** String of bits from decompression **********\n");
	str_bit2 = decompress(bits, nbits);
	printf("%s\n\n", str_bit2);
	final_str = decode(head, str_bit2);
	printf("********** String generated by decode **********\n");
	printf("%s\n\n", final_str);
	free(freq);
	free_tree(head);
	free_dictionary(d);
	free(str_bit1);
	free(bits);
	free(str_bit2);
	free(final_str);
}
