/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   encoder.c                                          :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: sguilher <sguilher@student.42sp.org.br>    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/01/10 10:25:28 by sguilher          #+#    #+#             */
/*   Updated: 2023/01/13 16:28:38 by sguilher         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "encoder.h"

/* Encoder:
	open file
	read file
	apply huffman coding
	6. Send the encoded text to the shared memory
	7. Read the info from the decoder and display it
	close file
	*/

/* Decoder:
	open file
	read file
	1. Aplly the translation table */

int	encoder(unsigned char *strs)
{
	unsigned char	*initial_str;
	unsigned int	*freq;
	t_huffman		*head;
	char			**d;
	char			*str_bit;
	size_t			nbits;
	unsigned char	*bits;

	// verificar se a string recebida é nula -> transformar em ""
	// juntar as strings
	printf("********** Initial string **********\n");
	initial_str = strs;
	printf("%s\n\n", initial_str);

	freq = huffman_frequency(initial_str);
	head = create_huffman_lst(freq);
	head = create_huffman_tree(&head);
	d = dictionary(head);

	printf("********** String of bits from encode **********\n");
	str_bit = encode(d, initial_str);
	printf("%s\n\n", str_bit);

	printf("********** String generated by compression **********\n");
	nbits = number_of_bits(str_bit);
	bits = compress(str_bit, nbits);
	printf("%s\n\n", bits);

	free(freq);
	free_tree(head);
	free_dictionary(d);
	free(str_bit);
	free(bits);
	//(void)nstrs;
	return (0);
}
