/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: sguilher <sguilher@student.42sp.org.br>    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/01/13 11:41:30 by sguilher          #+#    #+#             */
/*   Updated: 2023/01/13 20:34:56 by sguilher         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "encoder.h"

int	main(int argc, char *argv[])
{
	unsigned char	*text;
	int				block_id;
	char			*shared_memory;
	char			*str_bit;
	char			*bits;

	if (argc == 1)
	{
		printf("No data received by encoder\n");
		printf("usage - %s [\"str1\"] [\"str2\"] ... (data to compress)", argv[0]);
		//printf("usage - %s -f [filename]", argv[0]);
		return (1);
	}

	block_id = create_shared_block(FILENAME, BLOCK_SIZE, 0);
	printf("block_id = %i\n", block_id);
	shared_memory = attach_memory_block(block_id);
	if (shared_memory == NULL)
		return (printf("Error creating shared memory for encoder\n"));

	// tratar os inputs recebidos para ficar com apenas uma string
	// verificar se a string recebida é nula ou vazia e retornar
	text = (unsigned char *)argv[1];
	printf("********** Initial string **********\n");
	printf("%s\n\n", text);

	printf("********** Encoded string **********\n");
	str_bit = encode((unsigned char *)text);
	printf("%s\n\n", str_bit);

	printf("********** String generated by compression **********\n");
	bits = compress(str_bit);
	printf("%s\n\n", bits);

	// escrever na shared memory
	strncpy(shared_memory, bits, BLOCK_SIZE);
	dettach_memory_block(shared_memory);
	free(bits);
	return (0);
}
