/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   decoder.c                                          :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: sguilher <sguilher@student.42sp.org.br>    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/01/13 13:35:16 by sguilher          #+#    #+#             */
/*   Updated: 2023/01/13 15:43:38 by sguilher         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "decoder.h"

int	decoder(int nbits, char *bits)
{
	unsigned int	*freq;
	t_huffman		*head;
	char			*str_bit;
	unsigned char	*final_str;

	printf("********** String of bits from decompression **********\n");
	str_bit = decompress((unsigned char *)bits, nbits);
	printf("%s\n\n", str_bit);

	printf("********** String generated by decode **********\n");
	freq = huffman_frequency((unsigned char *)"Hello World");
	head = create_huffman_lst(freq);
	head = create_huffman_tree(&head);
	final_str = decode(head, str_bit);
	printf("%s\n\n", final_str);

	free(freq); //
	free_tree(head);
	free(str_bit);
	free(final_str);
	return (0);
}
